# -- MXRaceHub Site Configuration --
# Using Custom Theme based on Blowfish

theme = ["blowfish"]
disableKinds = []
ignoreFiles = []
baseURL = "https://mxracehub.github.io.git/"
defaultContentLanguage = "en"
disableLanguages = ["it", "ja", "zh-cn"] # Only use English for MXRaceHub

enableRobotsTXT = true
summaryLength = 30
hasCJKLanguage = false

buildDrafts = false
buildFuture = false

enableEmoji = true

# Site title and description
title = "MXRaceHub"
copyright = "© 2025 MXRaceHub - Supercross and Motocross Fan Platform"

[pagination]
  pagerSize = 100

[imaging]
  anchor = 'Center'

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"

[sitemap]
  changefreq = 'always'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]

[related]
  threshold = 0
  toLower = false

    [[related.indices]]
        name = "tags"
        weight = 100

    [[related.indices]]
        name = "categories"
        weight = 100

    [[related.indices]]
        name = "series"
        weight = 50

    [[related.indices]]
        name = "authors"
        weight = 20

    [[related.indices]]
        name = "date"
        weight = 10

    [[related.indices]]
      applyFilter = false
      name = 'fragmentrefs'
      type = 'fragments'
      weight = 10
