# Spanish Language Configuration for MXRaceHub
languageCode = "es"
languageName = "Español"
weight = 2

title = "MXRaceHub - Plataforma Definitiva de Supercross y Motocross"

# Footer content
copyright = "© 2025 MXRaceHub - Plataforma de Fanáticos de Supercross y Motocross"

[params]
  description = "MXRaceHub es la plataforma definitiva para fanáticos del Supercross y Motocross. Obtén horarios de carreras en vivo, cuotas de apuestas, perfiles de pilotos, información de pistas y cobertura completa del campeonato."
  displayName = "ES"
  isoCode = "es"
  rtl = false
  
  # Navigation and UI translations
  mainSections = ["carreras", "pilotos", "pistas", "apuestas"]
  
  # Site specific parameters
  author = "Equipo MXRaceHub"
  keywords = ["supercross", "motocross", "AMA", "carreras", "apuestas", "pilotos", "pistas", "campeonato", "deportes de motor", "dirt bike"]
  
  # Social media
  twitter_site = "@mxracehub"
  
  # UI Text translations
  [params.ui]
    readingTime = "tiempo de lectura"
    words = "palabras"
    minute = "min"
    minutes = "mins"
    
  # Navigation translations
  [params.nav]
    home = "Inicio"
    races = "Carreras"
    riders = "Pilotos"
    tracks = "Pistas"
    betting = "Apuestas"
    schedule = "Horarios"
    standings = "Clasificaciones"
    
  # Common action words
  [params.actions]
    readMore = "Leer más"
    viewAll = "Ver todo"
    login = "Iniciar sesión"
    logout = "Cerrar sesión"
    register = "Registrarse"
    placeBet = "Apostar"
    viewProfile = "Ver perfil"
    
  # Time and date
  [params.time]
    dateFormat = "2 January 2006"
    timeFormat = "15:04"
    
  # Betting specific
  [params.betting]
    odds = "Cuotas"
    bet = "Apuesta"
    winner = "Ganador"
    place = "Lugar"
    show = "Mostrar"