# English Language Configuration for MXRaceHub
languageCode = "en"
languageName = "English"
weight = 1

title = "MXRaceHub - Ultimate Supercross and Motocross Platform"

# Footer content
copyright = "© 2025 MXRaceHub - Supercross and Motocross Fan Platform"

[params]
  description = "MXRaceHub is the ultimate platform for Supercross and Motocross fans. Get live race schedules, betting odds, rider profiles, track information, and complete championship coverage."
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  
  # Navigation and UI translations
  mainSections = ["races", "riders", "tracks", "betting"]
  
  # Site specific parameters
  author = "MXRaceHub Team"
  keywords = ["supercross", "motocross", "AMA", "racing", "betting", "riders", "tracks", "championship", "motorsports", "dirt bike"]
  
  # Social media
  twitter_site = "@mxracehub"
  
  # UI Text translations
  [params.ui]
    readingTime = "reading time"
    words = "words"
    minute = "min"
    minutes = "mins"
    
  # Navigation translations
  [params.nav]
    home = "Home"
    races = "Races"
    riders = "Riders"
    tracks = "Tracks"
    betting = "Betting"
    schedule = "Schedule"
    standings = "Standings"
    
  # Common action words
  [params.actions]
    readMore = "Read more"
    viewAll = "View all"
    login = "Log in"
    logout = "Log out"
    register = "Register"
    placeBet = "Place bet"
    viewProfile = "View profile"
    
  # Time and date
  [params.time]
    dateFormat = "2 January 2006"
    timeFormat = "15:04"
    
  # Betting specific
  [params.betting]
    odds = "Odds"
    bet = "Bet"
    winner = "Winner"
    place = "Place"
    show = "Show"