# Italian Language Configuration for MXRaceHub
languageCode = "it"
languageName = "Italiano"
weight = 3

title = "MXRaceHub - Piattaforma Definitiva per Supercross e Motocross"

# Footer content
copyright = "© 2025 MXRaceHub - Piattaforma per Appassionati di Supercross e Motocross"

[params]
  description = "MXRaceHub è la piattaforma definitiva per appassionati di Supercross e Motocross. Ottieni orari delle gare in diretta, quote delle scommesse, profili dei piloti, informazioni sui circuiti e copertura completa del campionato."
  displayName = "IT"
  isoCode = "it"
  rtl = false
  
  # Navigation and UI translations
  mainSections = ["gare", "piloti", "circuiti", "scommesse"]
  
  # Site specific parameters
  author = "Team MXRaceHub"
  keywords = ["supercross", "motocross", "AMA", "gare", "scommesse", "piloti", "circuiti", "campionato", "sport motoristici", "dirt bike"]
  
  # Social media
  twitter_site = "@mxracehub"
  
  # UI Text translations
  [params.ui]
    readingTime = "tempo di lettura"
    words = "parole"
    minute = "min"
    minutes = "mins"
    
  # Navigation translations
  [params.nav]
    home = "Home"
    races = "Gare"
    riders = "Piloti"
    tracks = "Circuiti"
    betting = "Scommesse"
    schedule = "Programma"
    standings = "Classifica"
    
  # Common action words
  [params.actions]
    readMore = "Leggi di più"
    viewAll = "Vedi tutto"
    login = "Accedi"
    logout = "Esci"
    register = "Registrati"
    placeBet = "Scommetti"
    viewProfile = "Vedi profilo"
    
  # Time and date
  [params.time]
    dateFormat = "2 January 2006"
    timeFormat = "15:04"
    
  # Betting specific
  [params.betting]
    odds = "Quote"
    bet = "Scommessa"
    winner = "Vincitore"
    place = "Piazzamento"
    show = "Mostra"