[goldmark]
[goldmark.renderer]
unsafe = true
hardWraps = false
xhtml = false

[goldmark.extensions]
typographer = true
definitionList = true
footnote = true
linkify = true
strikethrough = true
table = true
taskList = true

[goldmark.extensions.typographer]
apostrophe = true
disable = false
ellipsis = true
emDash = true
enDash = true
quotes = true

[goldmark.parser]
autoHeadingID = true
autoHeadingIDType = "github"

[goldmark.parser.attribute]
block = true
title = true

[highlight]
noClasses = false

[tableOfContents]
startLevel = 2
endLevel = 4