
[goldmark]
[goldmark.renderer]
  unsafe = true
  
[goldmark.parser]
  autoHeadingID = true
  wrapStandAloneImageWithinParagraph = true

[highlight]
  noClasses = false

[tableOfContents]
  startLevel = 2
  endLevel = 4
