# -- MXRaceHub Menù Principale (Italiano) --
# Navigazione principale per la nostra piattaforma di Supercross e Motocross

[[main]]
  name = "Home"
  pageRef = "/"
  weight = 10

[[main]]
  name = "Gare"
  pageRef = "races/"
  weight = 20

[[main]]
  name = "Piloti"
  pageRef = "riders/"
  weight = 30

[[main]]
  name = "Circuiti"
  pageRef = "tracks/"
  weight = 40

[[main]]
  name = "Scommesse"
  pageRef = "betting/"
  weight = 50

[[main]]
  name = "Notizie"
  pageRef = "news/"
  weight = 60

[[main]]
  name = "Guarda Live"
  pageRef = "watch/"
  weight = 70

[[main]]
  identifier = "instagram"
  pre = "instagram"
  url = "https://instagram.com/mxracehub"
  weight = 100

[[main]]
  identifier = "twitter"
  pre = "x-twitter"
  url = "https://twitter.com/mxracehub"
  weight = 110

[[main]]
  identifier = "language-switch"
  name = "EN"
  url = "/"
  weight = 120
  [main.params]
    class = "language-switch"
    title = "Switch to English"


# -- MXRaceHub Menù del Piè di Pagina --
# Collegamenti visualizzati in fondo a tutte le pagine

[[footer]]
  name = "Chi Siamo"
  pageRef = "about/"
  weight = 10

[[footer]]
  name = "Contatti"
  pageRef = "contact/"
  weight = 20

[[footer]]
  name = "Termini"
  pageRef = "terms/"
  weight = 30

[[footer]]
  name = "Privacy"
  pageRef = "privacy/"
  weight = 40

[[footer]]
  name = "Politiche Scommesse"
  pageRef = "betting/policies/"
  weight = 50