# -- MXRaceHub Main Menu --
# Main navigation for our Supercross and Motocross platform

[[main]]
  name = "Home"
  pageRef = "/"
  weight = 10

[[main]]
  name = "Races"
  pageRef = "races/"
  weight = 20

[[main]]
  name = "Riders"
  pageRef = "riders/"
  weight = 30

[[main]]
  name = "Tracks"
  pageRef = "tracks/"
  weight = 40

[[main]]
  name = "Betting"
  pageRef = "betting/"
  weight = 50

[[main]]
  name = "News"
  pageRef = "news/"
  weight = 60

[[main]]
  name = "Watch Live"
  pageRef = "watch/"
  weight = 70

[[main]]
  identifier = "instagram"
  pre = "instagram"
  url = "https://instagram.com/mxracehub"
  weight = 100

[[main]]
  identifier = "twitter"
  pre = "x-twitter"
  url = "https://twitter.com/mxracehub"
  weight = 110


# -- MXRaceHub Footer Menu --
# Links displayed at the bottom of all pages

[[footer]]
  name = "About"
  pageRef = "about/"
  weight = 10

[[footer]]
  name = "Contact"
  pageRef = "contact/"
  weight = 20

[[footer]]
  name = "Terms"
  pageRef = "terms/"
  weight = 30

[[footer]]
  name = "Privacy"
  pageRef = "privacy/"
  weight = 40

[[footer]]
  name = "Betting Policies"
  pageRef = "betting/policies/"
  weight = 50
