# -- MXRaceHub Menú Principal (Español) --
# Navegación principal para nuestra plataforma de Supercross y Motocross

[[main]]
  name = "Inicio"
  pageRef = "/"
  weight = 10

[[main]]
  name = "Carreras"
  pageRef = "races/"
  weight = 20

[[main]]
  name = "Pilotos"
  pageRef = "riders/"
  weight = 30

[[main]]
  name = "Pistas"
  pageRef = "tracks/"
  weight = 40

[[main]]
  name = "Apuestas"
  pageRef = "betting/"
  weight = 50

[[main]]
  name = "Noticias"
  pageRef = "news/"
  weight = 60

[[main]]
  name = "Ver En Vivo"
  pageRef = "watch/"
  weight = 70

[[main]]
  identifier = "instagram"
  pre = "instagram"
  url = "https://instagram.com/mxracehub"
  weight = 100

[[main]]
  identifier = "twitter"
  pre = "x-twitter"
  url = "https://twitter.com/mxracehub"
  weight = 110

[[main]]
  identifier = "language-switch"
  name = "EN"
  url = "/"
  weight = 120
  [main.params]
    class = "language-switch"
    title = "Switch to English"


# -- MXRaceHub Menú del Pie de Página --
# Enlaces mostrados en la parte inferior de todas las páginas

[[footer]]
  name = "Acerca"
  pageRef = "about/"
  weight = 10

[[footer]]
  name = "Contacto"
  pageRef = "contact/"
  weight = 20

[[footer]]
  name = "Términos"
  pageRef = "terms/"
  weight = 30

[[footer]]
  name = "Privacidad"
  pageRef = "privacy/"
  weight = 40

[[footer]]
  name = "Políticas de Apuestas"
  pageRef = "betting/policies/"
  weight = 50