# -- MXRaceHub メインメニュー (日本語) --
# スーパークロス・モトクロスプラットフォームのメインナビゲーション

[[main]]
  name = "ホーム"
  pageRef = "/"
  weight = 10

[[main]]
  name = "レース"
  pageRef = "races/"
  weight = 20

[[main]]
  name = "ライダー"
  pageRef = "riders/"
  weight = 30

[[main]]
  name = "トラック"
  pageRef = "tracks/"
  weight = 40

[[main]]
  name = "ベッティング"
  pageRef = "betting/"
  weight = 50

[[main]]
  name = "ニュース"
  pageRef = "news/"
  weight = 60

[[main]]
  name = "ライブ視聴"
  pageRef = "watch/"
  weight = 70

[[main]]
  identifier = "instagram"
  pre = "instagram"
  url = "https://instagram.com/mxracehub"
  weight = 100

[[main]]
  identifier = "twitter"
  pre = "x-twitter"
  url = "https://twitter.com/mxracehub"
  weight = 110

[[main]]
  identifier = "language-switch"
  name = "EN"
  url = "/"
  weight = 120
  [main.params]
    class = "language-switch"
    title = "Switch to English"


# -- MXRaceHub フッターメニュー --
# 全ページ下部に表示されるリンク

[[footer]]
  name = "概要"
  pageRef = "about/"
  weight = 10

[[footer]]
  name = "お問い合わせ"
  pageRef = "contact/"
  weight = 20

[[footer]]
  name = "利用規約"
  pageRef = "terms/"
  weight = 30

[[footer]]
  name = "プライバシー"
  pageRef = "privacy/"
  weight = 40

[[footer]]
  name = "ベッティングポリシー"
  pageRef = "betting/policies/"
  weight = 50