# -- MXRaceHub Theme Options --
# Customized for Supercross/Motocross fan platform

colorScheme = "orange" # Custom color scheme for motocross theme
defaultAppearance = "dark" # Motocross websites often use dark themes
autoSwitchAppearance = true

enableSearch = false
enableCodeCopy = false # No need for code copy in racing fan site

replyByEmail = false

# Main content sections for the site
mainSections = ["races", "riders", "tracks", "betting", "news"]

disableImageOptimization = false
disableTextInHeader = false

# Disable problematic JS features that cause errors
disableImageZoom = true
disableJavaScript = true
enableImageZoom = false

# Using custom SVG images that show rider numbers and manufacturer logos
defaultBackgroundImage = "/img/hero/motocross-action.svg"
defaultFeaturedImage = "/img/hero/hero-background.svg"

highlightCurrentMenuArea = true
smartTOC = true
smartTOCHideUnfocusedChildren = false

[header]
  layout = "custom" # Using our custom MXRaceHub header instead of theme options

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = false # Remove theme attribution
  showAppearanceSwitcher = true
  showScrollToTop = false

[homepage]
  layout = "custom-race" # Using our custom layout for race-focused homepage
  homepageImage = "/img/hero/motocross-action.svg" # Motocross hero image
  showRecent = true
  showRecentItems = 6 # Show more races on the homepage
  showMoreLink = true
  showMoreLinkDest = "races" # Point to races section
  cardView = true
  cardViewScreenWidth = true
  layoutBackgroundBlur = false # Keep background sharp for racing imagery

[article]
  showDate = true # Show dates for race events
  showViews = false
  showLikes = false
  showDateOnlyInArticle = false
  showDateUpdated = true # Show when race info is updated
  showAuthor = true
  showHero = true
  heroStyle = "big" # Larger hero images for race/rider content
  layoutBackgroundBlur = false # Keep racing images sharp
  showBreadcrumbs = true
  showDraftLabel = false # No draft content for production
  showEdit = false # Disable edit links
  seriesOpened = true # For race series
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = false # Not relevant for race info
  showTableOfContents = true
  showRelatedContent = true
  relatedContentLimit = 4 # Show related races/riders
  showTaxonomies = true 
  showAuthorsBadges = false # Not using multiple authors
  showWordCount = false
  sharingLinks = ["twitter", "facebook", "reddit", "whatsapp", "email"] # Simplified sharing options
  showZenMode = false # Not needed for race content

[list]
  showHero = true
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  layoutBackgroundBlur = true # only used when heroStyle equals background
  layoutBackgroundHeaderSpace = false
  showBreadcrumbs = false
  showSummary = false
  showViews = false
  showLikes = false
  showTableOfContents = true
  showCards = true
  orderByWeight = true
  groupByYear = false
  cardView = true
  cardViewScreenWidth = false
  constrainItemsWidth = false

[sitemap]
  excludedKinds = []

[taxonomy]
  showTermCount = true
  showHero = true
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = true
  cardView = false

[term]
  showHero = true
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = true
  groupByYear = false
  cardView = true
  cardViewScreenWidth = false
  
[firebase]
  #apiKey = "AIzaSyB5tqlqDky77Vb4Tc4apiHV4hRZI18KGiY"
  #authDomain = "blowfish-21fff.firebaseapp.com"
  #projectId = "blowfish-21fff"
  #storageBucket = "blowfish-21fff.appspot.com"
  #messagingSenderId = "60108104191"
  #appId = "1:60108104191:web:039842ebe1370698b487ca"
  #measurementId = "G-PEDMYR1V0K"

[fathomAnalytics]
  # site = "ABC12345"
  # domain = "llama.yoursite.com"

[umamiAnalytics]
  # websiteid = "ABC12345"
  # domain = "llama.yoursite.com"
  # dataDomains = "yoursite.com,yoursite2.com"
  # scriptName = ""
  # enableTrackEvent = false

[selineAnalytics]
  # token = "XXXXXX"
  # enableTrackEvent = false

[buymeacoffee]
  identifier = "nunocoracao"
  globalWidget = true
  globalWidgetMessage = ""
  globalWidgetColor = "#FFDD00"
  globalWidgetPosition = "Right"

[verification]
  # google = ""
  # bing = ""
  # pinterest = ""
  # yandex = ""

[rssnext]
  # feedId = ""
  # userId = ""